on:
  telegram_bot:
    token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
jobs:
  ifttt:
    name: Make a Request to IFTTT
    runs-on: ubuntu-latest
    steps:
      - uses: hugoalh/GitHubAction.SendToIFTTT@v1.1.7
        with:
          webhook_eventname: test
          webhook_key: ${{ secrets.IFTTT_KEY }}
          value1: ${{ toJson(on.telegram_bot.outputs) }}
