on:
  webhook:
    event_type: test
jobs:
  ifttt:
    name: Make a Request to IFTTT
    runs-on: ubuntu-latest
    steps:
      - uses: alfredosalzillo/ifttt-webhook-action@v1
        with:
          event: test
          key: ${{ secrets.IFTTT_KEY }}
          value1: ${{toJson(on.webhook.outputs.payload)}}
          value2: ${{toJson(on.webhook.outputs.body)}}
