on:
  poll:
    url: https://jsonplaceholder.typicode.com/posts
    max_items_count: 5
jobs:
  ifttt:
    name: Make a Request to IFTTT
    runs-on: ubuntu-latest
    steps:
      - uses: alfredosalzillo/ifttt-webhook-action@v1
        with:
          event: test
          key: ${{ secrets.IFTTT_KEY }}
          value1: ${{ on.poll.outputs.id }}
          value2: ${{ toJson(on.poll.outputs) }}
