name: Actions Run
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - id: test_secrets
        name: get secrets
        uses: actions/github-script@v2
        env:
          JSON_SECRETS: ${{ toJson(secrets) }}
          JSON_GITHUB: ${{ toJson(github) }}
        with:
          script: |
            const secrets = JSON.parse(process.env.JSON_SECRETS);
            const github2 = JSON.parse(process.env.JSON_GITHUB);
            console.log('secrets',secrets)
            console.log('github2',JSON.stringify(github2,null,2))
            console.log('context',JSON.stringify(context,null,2))
          result-encoding: string
      - run: node -v
      - run: yarn
      - run: yarn build
      - run: curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
      - run: act -W ./dist/workflows --secret-file ./dist/.secrets
