"on":
  push: null
jobs:
  ifttt:
    name: Make a Request to IFTTT
    runs-on: ubuntu-latest
    steps:
      - uses: actionflow/ifttt-webhook-action@master
        with:
          event: test
          key: ${{ secrets.IFTTT_KEY }}
          value1: 111
          value2: 222
          value3: 333
