name: Actions Run
on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    env:
      CACHE_BRANCH: cache
      LOCAL_CACHE_DIR: .last-build-cache
      CACHE_KEY_FILE: .latest-build-cache-key
      JSON_SECRETS: ${{ toJson(secrets) }}
      JSON_GITHUB: ${{ toJson(github) }}
    steps:
      - uses: actions/checkout@v2
      - name: test env
        uses: actions/github-script@v2
        with:
          script: |
            const secrets = JSON.parse(process.env.JSON_SECRETS);
            const github2 = JSON.parse(process.env.JSON_GITHUB);
            console.log('secrets',secrets)
            console.log('github2',JSON.stringify(github2,null,2))
            console.log('context',JSON.stringify(context,null,2))
          result-encoding: string
      - id: isCacheBranchExist
        name: If cache branch exist
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            return github.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: process.env.CACHE_BRANCH
            }).then(data=>{
              return true;
            }).catch((e)=>{
              if(e && e.status===404){
                // then manual trigger
                return false
              }else{
                core.setFailed('check isDeployBranchExist error: ',e.message)
              }
            })
      - name: Get cache key from last build cache key
        id: last-cache-key-file-loaded
        if: steps.isCacheBranchExist.outputs.result == 'true'
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: ${{ env.CACHE_BRANCH }}
          path: ${{ env.LOCAL_CACHE_DIR }}
      - name: Get last cache key content
        if: ${{ steps.last-cache-key-file-loaded.outcome == 'success' }}
        id: last-cache-key
        run: echo "::set-output name=result::$(cat $LOCAL_CACHE_DIR/$CACHE_KEY_FILE)"
      - name: Restore cache directory
        uses: actions/cache@v2
        id: restore-cache
        if: ${{ steps.last-cache-key.outcome == 'success' }}
        with:
          key: ${{ runner.os }}-cache-${{ steps.last-cache-key.outputs.result }}
          path: .cache
      # - run: ls -l ./.cache/caches
      #   if: steps.restore-cache.outcome == 'success'
      # - run: ls -l ./.cache/caches/trigger-ef2bf44fd3010e5dac469f15f1279ef1
      #   if: steps.restore-cache.outcome == 'success'
      - run: ls -l ./.cache/caches

      - name: Get current cache dir hash
        id: current-cache-dir-hash
        uses: theowenyoung/folder-hash@v2
        with:
          path: .cache
      - env:
          CURRENT_CACHE_FOLDER_HASH: ${{ steps.current-cache-dir-hash.outputs.hash }}
        run: echo $CURRENT_CACHE_FOLDER_HASH && ls -l ./.cache/caches
      - run: yarn
      - run: yarn build
      - run: curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
      - run: act -r -W ./dist/workflows --secret-file ./dist/.secrets -e ./dist/event.json
      - name: Get latest cache dir hash
        id: latest-cache-dir-hash
        uses: theowenyoung/folder-hash@v2
        with:
          path: .cache
      - env:
          CURRENT_CACHE_FOLDER_HASH: ${{ steps.current-cache-dir-hash.outputs.hash }}
          LATEST_CACHE_FOLDER_HASH: ${{ steps.latest-cache-dir-hash.outputs.hash }}
          LAST_CACHE_FOLDER_HASH: ${{ steps.last-cache-key.outputs.result }}
        run: echo $CURRENT_CACHE_FOLDER_HASH && echo $LATEST_CACHE_FOLDER_HASH && echo $LAST_CACHE_FOLDER_HASH && ls -l ./.cache/caches

      - name: upload cache
        # if: steps.latest-cache-dir-hash.outputs.hash != steps.latest-cache-key.outputs.result
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-cache-${{ steps.latest-cache-dir-hash.outputs.hash}}
          path: .cache
      - name: Save cache key to file
        # if: steps.latest-cache-dir-hash.outputs.hash != steps.latest-cache-key.outputs.result
        run: mkdir ./public && echo ${{ steps.latest-cache-dir-hash.outputs.hash}} > ./public/$CACHE_KEY_FILE
      - name: Push cache branch
        # if: steps.latest-cache-dir-hash.outputs.hash != steps.latest-cache-key.outputs.result
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: ${{ env.CACHE_BRANCH }}
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
